# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# jb clean portfolio-book/ --all
# jb build portfolio-book
# ghp-import -n -p -f portfolio-book/_build/html

title: Fahmi's Portfolio
author: Fahmi I.
copyright: '2022'
# logo: 

# Execution settings
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/fahm1/Portfolio  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# HTML-specific settings
html:
  # baseurl: 
  favicon: "favicon.ico"
  use_issues_button: true
  use_repository_button: true
  # comments:
  #   utterances:
  #     repo: https://github.com/fahm1/Portfolio   

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      extra_navbar: ""
      show_toc_level: 2

# launch_buttons:
#   binderhub_url: ""
#   notebook_interface: "jupyterhub"

# sphinx:
#   recursive_update: false
#   config:
#     html_theme: "pydata_sphinx_theme"
#     html_context:
#       default_mode: "light"
#     html_theme_options:
#       pygment_light_style: "manni"
#       pygment_dark_style: "monokai"
#       search_bar_text: "Search here..."
#       show_nav_level: 1
#       icon_links: [
#         name: "Github",
#         url: "https://github.com/fahm1/Portfolio",
#         icon: "fab fa-github"]
#       # navbar_start: ["navbar-logo"]
#       navbar_center: ""
#       navbar_end: ["navbar-icon-links"]



# html_theme_options = {'search_bar_text': 'Search this book...', 
#                       'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': 'https://mybinder.org', 'jupyterhub_url': '', 'thebe': False, 'colab_url': ''}, 
#                       'path_to_docs': 'docs', 
#                       'repository_url': 'https://github.com/fahm1/Portfolio', 
#                       'repository_branch': 'master', 'google_analytics_id': '', 
#                       'extra_navbar': 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>', 
#                       'extra_footer': '', 
#                       'home_page_in_toc': True, 
#                       'announcement': '', 
#                       'use_repository_button': True, 
#                       'use_edit_page_button': False, 
#                       'use_issues_button': True, 
#                       'icon_links': {'name': 'Github', 'url': 'https://github.com/fahm1/Portfolio', 
#                                      'icon': 'fab fa-github'}}