# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# jb clean portfolio-book/ --all
# jb build portfolio-book
# ghp-import -n -p -f portfolio-book/_build/html

title: Fahmi's Portfolio
author: Fahmi I.
# copyright: '2022'
# logo: 

# Execution settings
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/fahm1/Portfolio  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# HTML-specific settings
html:
  # baseurl: 
  favicon: "favicon.ico"
  use_issues_button: true
  use_repository_button: true
  # comments:
  #   utterances:
  #     repo: https://github.com/fahm1/Portfolio   

sphinx:
  recursive_update: true
  config:
    language: en
    html_show_copyright: false
    html_theme_options:
      extra_navbar: ""
      show_toc_level: 2
