#!/usr/bin/env python
# coding: utf-8

# ```{image} bellabeat_banner.png
# :align: left
# :width: 100%
# ```

# # Bellabeat Case Study

# **Name:** Fahmi I.  
# **Date:** June 8th, 2022
# 
# This analysis will be broken down into 6 distinct phases:
# 1. __Introduction__ - Introduce the company and their products. 
# 1. __Ask__ - Identify the business problem at hand and how insights from the data can drive business decisions. 
# 2. __Prepare__ - Identify and gather relevant data and organize all files.
# 3. __Process__ - Use tools to glean basic information from the data while cleaning up and validating the data. 
# 4. __Analyze and Share__ - Perform calculations, identify trends and relationships, and create visualizations to tackle the business question. 
# 5. __Act__ - Provide final recommendations for the business and how to move forward by making data-driven decisions. 
# 
# ```{tip}
# A table of contents for this notebook can be found on the top-right corner of this page. 
# ```
# 
# ---

# <!-- ## <span style="color:#FA8072">Table of Contents</span>
# 
# * [1. Introduction](#Introduction)
# * [2. Ask Phase](#Ask-Phase)
# * [3. Prepare Phase](#Prepare-Phase)
#     * [3.1 Business Task](#Business-Task)
# * [4. Process Phase](#Process-Phase)
# * [5. Analyze and Share Phase](#Analyze-and-Share-Phase)
# * [6. Act Phase](#Act-Phase)
# 
# --- -->

# ## 1. Introduction

# Bellabeat is a small high-tech manufacturer of health-focused products with dreams to become a larger player in the global [smart device](https://en.wikipedia.org/wiki/Smart_device) industry. 
# The main focus of this case study is to analyze the health data collected from smart devices to determine new growth opportunities for the company. 
# 
# Here is a brief overview the company's products:
# ````{margin}
# ```{note}
# The Bellabeat Leaf, Time, and Spring all communicate through the app to provide users with personalized recommendations and detailed statistics. 
# ```
# ````
# * __Bellabeat App:__ An mobile app that tracks users' health data and provides personalized recommendations based on the data. 
# * __Bellabeat Membership:__ A subscription service that gives members 24/7 access to personalized recommendations on nutrition, activity, sleep, health, and beauty based on their lifestyle and goals. 
# * __Leaf__: A wellness tracker that can be worn as a bracelet, necklace, or clip to record user activity, sleep, and stress. 
# * __Time__: A wellness watch that looks like a classic watch while also tracking user activity, sleep, and stress.  
# * __Spring__: A smart water bottle that can be used to track user hydration and water intake.

# ---

# ## 2. Ask

# ### 2.1 Business Task
# Analyze __non-Bellabeat__ smart device usage to gain insight on how consumers use their smart devices and discover trends that could be used to improve Bellabeat's marketing strategy. 
# 
# Guiding Questions:
# 1. What are some trends in smart device usage? 
# 1. How could these trends apply to Bellabeat customers?
# 1. How could these trends help influence Bellabeat's marketing strategy?
# 
# ### 2.2 Stakeholders
# As insights from this case study will influence Bellabeat's marketing strategy, the following stakeholders will be involved:
# 
# * __Urška Sršen:__ Cofounder and Chief Creative Officer of Bellabeat
# * __Sando Mur:__ Mathematician and Bellabeat’s cofounder; key member of the Bellabeat executive team
# * __Bellabeat marketing analytics team:__ A team of data analysts responsible for collecting, analyzing, and reporting data that helps guide Bellabeat’s marketing strategy

# ---

# ## 3. Prepare 

# ### 3.1 Dataset Information
# ````{margin}
# ```{note}
# The dataset is a public dataset with a CC0: Public Domain license. 
# ```
# ````
# The dataset used for this case study is the [FitBit Fitness Tracker Data](https://www.kaggle.com/datasets/arashnic/fitbit/metadata) shared by [Mobius](https://www.kaggle.com/arashnic) on [Kaggle](https://www.kaggle.com).
# 
# This Kaggle dataset contains personal fitness tracker from thirty fitbit users. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring. It includes information about daily activity, steps, and heart rate that can be used to explore users’ habits. 
# 
# The data was generated by respondents to a distributed survey via Amazon Mechanical Turk from March 3rd, 2016 to May 12th, 2016. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring.
# 
# ### 3.2 Data Description
# 
# There are 18 CSV files in the dataset containing the various data tracked by Fitbit. The data includes quantitative measures of activity, calories burned, intensity, steps, sleep, and weight.  
# Detailed descriptions of each file and column can be found [here](https://www.fitabase.com/media/1930/fitabasedatadictionary102320.pdf).
# 
# ```{dropdown} Click here for a table with a description of each CSV file.
# | Table Name | Description |
# | --- | --- |
# | hourlyCalories_merged | Hourly calories burned over 31 days for 33 users |
# | dailyCalories_merged | Daily calories over 31  days for 33 users |
# | minuteCaloriesNarrow_merged | Calories burned every minute over 31 days for 33 users (every minute in single row)|
# | minuteCaloriesWide_merged | Calories burned every minute over 31 days for 33 users (every minute in single column)|
# | dailyIntensities_merged | Daily intensity over 31 days for 33 users. Measured in minutes and distance with 4 distinct categories: Sedentary, Lightly Active, Fairly Active,Very Active |
# | hourlyIntensities_merged | Hourly total and average intensity over 31 days for 33 users |
# | minuteIntensitiesNarrow_merged | Intensity recorded by minute over 31 days for 33 users (every minute in single row) |
# | minuteIntensitiesWide_merged | Intensity recorded by minute over 31 days for 33 users (every minute in single column)|
# | dailySteps_merged | Daily steps over 31 days for 33 users | 
# | hourlySteps_merged | Hourly steps over 31 days for 33 users |
# | minuteStepsNarrow_merged | Steps recorded by minute over 31 days for 33 users (every minute in single row)|
# | minuteStepsWide_merged | Steps recorded by minute over 31 days for 33 users (every minute in single column) |
# | dailyActivity_merged | Daily activity over 31 days for 33 users. Includes daily steps, distance, intensities, and calories burned |
# | sleepDay_merged | Sleep recorded by day, including count for number of sleeping periods per day, total minutes, and total time in bed |
# | minuteSleep_merged | Sleep recorded by minute for 24 users over 31 days. Values: 1 = asleep, 2 = restless, 3 = awake in bed |
# | heartrate_seconds_merged | Exact day and time heartrate logs for 7 users |
# | minuteMETsNarrow_merged | MET or metabolic equivalent of task value recorded in minutes |
# | weightLogInfo_merged | Weight and BMI recorded by day in Kg and Pounds over 30 days for 8 users |
# ```
# 
# ### 3.3 Data Integrity
# 
# There are certainly some limitations to the dataset:
# 
# * __Sample Size:__ The dataset contains only 33 users for many of the files, while other files contain recordings from even fewer users. 
# * __Study Duration:__ Much of the data was collected for a period of just one month, therefore lacking seasonal and other temporal trends. 
# * __Completion Date:__ The data was collected in mid-2016, which is about 6 years ago now. 
# 
# Noting these limitations, the recommendations and conclusions reached in this study will have to keep in mind that the data is not completely ideal. 
# However, identifying these limitations could lead to some generalized conclusions and may encourage seeking out other third-party data sources. 
# 
# `````{admonition} Key Takeaways:
# :class: tip
# The data is a public FitBit dataset that tracked various users' health data including calories burned and sleep. The data is limited in that it had a small sample size, short duration, and was completed years ago. 
# `````

# ---

# ## 4. Process 

# Due to the number of data files and their size, I will be using Python to process the data. 

# ### 4.1 Import Libraries and Read in Data

# Goals:
# * see the distribution of users in the 4 intensity categories
# * see average steps and calorie burn per category
# * see what time of day the users are most active
# * see average sleep and sleep per category
# use these conclusions to advertise how bellabeat membership and usage can lead to improvements in all of these 

# Starting off by importing the libraries we will need, all of which are standard for data analysis. 

# In[1]:


import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import os


# We can then take a look at which data files we have available.

# In[2]:


os.listdir(r'Data_Fitbase')


# We can now start reading in the files that we will be using in our analysis.  
# But first, we can create a simple function that will return important information about each created dataframe, such as the column names, shape, duplicate row count, and missing value count. 

# In[3]:


def df_info(df: pd.DataFrame, name: str='df', dup_rows: bool=True, missing_values: bool=True):
    '''Prints columns, shape, duplicate count, and null value count of a dataframe'''
    print(
    f'{name}:\n',
    f'\tColumns: {list(df.columns)}\n',
    f'\tShape: {df.shape}\n',
    f'\tDuplicate rows: {df.duplicated().sum()}\n' if dup_rows else '',
    f'\tMissing values: {df.isna().sum().sum()}' if missing_values else ''
    )


# Starting with the daily activity data, we will also create a copy of the dataframe in order to easily revert to the original data if needed:
# 
# ```{note}
# The names of the 'date' columns in each of the .csv files have already been identified using the [Fitabase description of the dataset](https://www.fitabase.com/media/1930/fitabasedatadictionary102320.pdf) in order to save time when changing the datatype of the 'date' columns from 'object' to 'datetime64[ns]'. 
# ```

# In[4]:


original_day_activity = pd.read_csv(
    r'C:\Users\fahmi\Documents\Portfolio\Large Files\Data_Fitbase/dailyActivity_merged.csv', 
    parse_dates=['ActivityDate'], infer_datetime_format=True
)
df_day_activity = original_day_activity.copy()
df_info(df=df_day_activity, name='df_day_activity')


# In[5]:


df_day_activity.head(3)


# We can then do the same with the hourly steps data:

# In[6]:


original_hour_steps = pd.read_csv(
    r'C:\Users\fahmi\Documents\Portfolio\Large Files\Data_Fitbase/hourlySteps_merged.csv',
    parse_dates=['ActivityHour'], infer_datetime_format=True
)
df_hour_steps = original_hour_steps.copy()
df_info(df=df_hour_steps, name='df_hour_steps')


# In[7]:


df_hour_steps.head(3)


# And the hourly calories burned data:

# In[8]:


original_hour_calories = pd.read_csv(
    r'C:\Users\fahmi\Documents\Portfolio\Large Files\Data_Fitbase/hourlyCalories_merged.csv',
    parse_dates=['ActivityHour'], infer_datetime_format=True
)
df_hour_calories = original_hour_calories.copy()
df_info(df=df_hour_calories, name='df_hour_calories')


# In[9]:


df_hour_calories.head(3)


# Then the daily sleep data:

# In[10]:


original_day_sleep = pd.read_csv(
    r'C:\Users\fahmi\Documents\Portfolio\Large Files\Data_Fitbase/sleepDay_merged.csv',
    parse_dates=['SleepDay'], infer_datetime_format=True
)
df_day_sleep = original_day_sleep.copy()
df_info(df=df_day_sleep, name='df_day_sleep')


# ```{admonition} Duplicate Data Warning:
# :class: warning
# Unlike with the other datafrarmes, we can see that there's actually 3 duplicate rows in the daily sleep data that we will take care of later. 
# ```

# In[11]:


df_day_sleep.head(3)


# And finally, the minute sleep data:

# In[12]:


original_min_sleep = pd.read_csv(
    r'C:\Users\fahmi\Documents\Portfolio\Large Files\Data_Fitbase/minuteSleep_merged.csv', 
    parse_dates=['date'], infer_datetime_format=False
)
df_min_sleep = original_min_sleep.copy()
df_info(df=df_min_sleep, name='df_min_sleep')


# ```{admonition} Duplicate Data Warning:
# :class: warning
# In the minute sleep data, we can see that there's 543 duplicate rows that we need to take care of as part of data cleaning. 
# ```

# In[13]:


df_min_sleep.head(3)


# ### 4.2 Data Cleaning
# 
# The first thing we should do as part of the data cleaning process is take care of the duplicate rows that we identified earlier in the ```df_day_sleep``` and ```df_min_sleep``` dataframes. 

# In[14]:


df_info(df=df_day_sleep, name='df_day_sleep')
df_info(df=df_min_sleep, name='df_min_sleep')


# In[15]:


df_day_sleep.drop_duplicates(keep='first', inplace=True)
df_info(df=df_day_sleep, name='df_day_sleep')


# In[16]:


df_min_sleep.drop_duplicates(keep='first', inplace=True)
df_info(df=df_min_sleep, name='df_min_sleep')


# And with that, we have made sure that there are no duplicate rows or null values in any of the dataframes.  
# Furthermore, we know that the data types of the columns are correct, as we have alerady parsed the 'date' columns in each of the dataframes, and pandas handles the rest of the columns automatically.  
# ```{tip}
# We are working with 5 dataframes in this analysis:
# * df_day_activity
# * df_hour_steps
# * df_hour_calories
# * df_day_sleep 
# * df_min_sleep
# ```
# 
# Now we can go on to eliminate columns that are unnecessary for our analysis, and rename columns as needed. 

# In[17]:


df_info(df=df_day_activity, name='df_day_activity', dup_rows=False, missing_values=False)


# In[18]:


columns_df_da = list(df_day_activity.columns.values)[4:-5]


# In[19]:


df_day_activity = df_day_activity.rename(columns={'ActivityDate': 'date', 'Id': 'id'})\
                                 .drop(columns=columns_df_da)
df_info(df=df_day_activity, name='df_day_activity', dup_rows=False, missing_values=False)


# <br>
# <br>

# In[20]:


df_info(df_hour_steps, name='df_hour_steps', dup_rows=False, missing_values=False)


# In[21]:


df_hour_steps = df_hour_steps.rename(columns={'Id': 'id', 'ActivityHour': 'date_time'})
df_info(df_hour_steps, name='df_hour_steps', dup_rows=False, missing_values=False)


# <br>
# <br>

# In[22]:


df_info(df_hour_calories, name='df_hour_calories', dup_rows=False, missing_values=False)


# In[23]:


df_hour_calories = df_hour_calories.rename(columns={'Id': 'id', 'ActivityHour': 'date_time'})
df_info(df_hour_calories, name='df_hour_calories', dup_rows=False, missing_values=False)


# <br>
# <br>

# In[24]:


df_info(df_day_sleep, name='df_day_sleep', dup_rows=False, missing_values=False)


# In[25]:


df_day_sleep = df_day_sleep.rename(columns={'Id': 'id', 'SleepDay': 'date'})
df_info(df_day_sleep, name='df_day_sleep', dup_rows=False, missing_values=False)


# <br>
# <br>

# In[26]:


df_info(df_min_sleep, name='df_min_sleep', dup_rows=False, missing_values=False)


# In[27]:


df_min_sleep = df_min_sleep.rename(columns={'Id': 'id', 'date': 'date_time'})\
                           .drop(columns='logId')
df_info(df_min_sleep, name='df_min_sleep', dup_rows=False, missing_values=False)


# ### 4.3 Merging Data
# 
# Now that the data is clean, we can merge some of the dataframes together.  
# ````{margin}
# ```{tip}
# An inner join is used in this case because we only want to keep the rows that are common between the merged dataframes. Using 'id' and a 'date' column as the primary key can ensure that corresponding rows get matched correctly. 
# ```
# ````
# We can merge the ```df_day_activity``` and ```df_day_sleep``` dataframes together to create a new dataframe called ```df_day_activity_sleep``` since their date columns are both 'date' instead of including a time element as well.  
# 
# Similarly, we can combine the ```df_hour_steps``` and ```df_hour_calories``` dataframes to create a new dataframe called ```df_hour_steps_calories``` since their date columns include a time element.  
# 
# Since no dataframe outside of ```df_min_sleep``` is on a minute-by-minute basis, we cannot combine the dataframe with the other dataframes.  
# 
# Doing inner joins with the ```id``` and either ```date``` or ```date_time``` columns as the primary key will allow us to join the dataframes together without losing any of the data and without creating extraneous columns or rows.  
# 
# Starting off with the  ```df_day_activity``` and ```df_day_sleep``` dataframes to make ```df_day_activity_sleep```:

# In[28]:


df_day_activity_sleep = df_day_sleep.merge(right=df_day_activity, on=['id', 'date'], 
                                           how='inner', validate='1:1')
df_info(df_day_activity_sleep, name='df_day_activity_sleep')


# In[29]:


df_day_activity_sleep.head(3)


# And then combining the ```df_hour_steps``` and ```df_hour_calories``` dataframes to make ```df_hour_steps_calories```:

# In[30]:


df_hour_steps_calories = df_hour_steps.merge(right=df_hour_calories, on=['id', 'date_time'],
                                             how='inner', validate='1:1')
df_info(df_hour_steps_calories, name='df_hour_steps_calories')


# In[31]:


df_hour_steps_calories.head(3)


# And our final dataframe, ```df_min_sleep```:

# In[32]:


df_min_sleep.head(3)


# ### 4.4 Adding Relevant Columns
# 
# For our now 3 dataframes, we can add a `day_of_week` column that will be used to identify the day of the week for each date. This may make it easier to visualize the data later on. 

# In[33]:


df_day_activity_sleep['day_of_week'] = df_day_activity_sleep['date'].dt.day_name()
df_hour_steps_calories['day_of_week'] = df_hour_steps_calories['date_time'].dt.day_name()
df_min_sleep['day_of_week'] = df_min_sleep['date_time'].dt.day_name()


# Then we can move the ```day_of_week``` column toward the front of the dataframe:

# In[34]:


day_of_week = df_day_activity_sleep['day_of_week']
df_day_activity_sleep.drop(columns='day_of_week', inplace=True)
df_day_activity_sleep.insert(loc=2, column='day_of_week', value=day_of_week)

day_of_week = df_hour_steps_calories['day_of_week']
df_hour_steps_calories.drop(columns='day_of_week', inplace=True)
df_hour_steps_calories.insert(loc=2, column='day_of_week', value=day_of_week)

day_of_week = df_hour_steps_calories['day_of_week']
df_min_sleep.drop(columns='day_of_week', inplace=True)
df_min_sleep.insert(loc=2, column='day_of_week', value=day_of_week)


# And taking a final quick look at the dataframes before analysis:

# In[35]:


df_day_activity_sleep.head(3)


# In[36]:


df_hour_steps_calories.head(3)


# In[37]:


df_min_sleep.head(3)


# ---

# ## 5. Analyze and Share 
# <!-- <a name='Analyze-and-Share-Phase'></a><h3 style="color:#FA8072">5. Analyze and Share Phase:</h3> -->

# With our data clean and processed, we can now begin to analyze the data to see how we can influence and improve Bellabeat's marketing decisions. 
# 
# ### 5.1 Activity Level Distribution

# First off, we can classify the individuals in the ```df_day_activity_sleep``` dataframe into 4 activity levels as adjusted from [10000steps.org.au](https://www.10000steps.org.au/articles/counting-steps/):
# 
# With this information, Bellabeat will be able to get an understanding of the demographics of users who use smart fitness devices like the FitBit, and an idea of what types of individuals they should focus their marketing efforts towards. 
# 
# * Sedentary: < 5,000 steps per day
# * Lightly Active: 5,000 - 7,499 steps per day
# * Fairly Active: 7,500 - 9,999 steps per day
# * Very Active: more than 10,000 steps per day
# 
# ```{note}
# [10000steps.org.au](https://www.10000steps.org.au/articles/counting-steps/) recommends that most adults take 10,000 steps daily as studies have shown that this level of activity leads to weight loss, better glucose tolerance, and reduced blood pressure. 
# ```
# 
# To do this, we can first find the average steps taken per day for each of the individuals in the ```df_day_activity_sleep``` dataframe.  
# In order to still be able to refer to ```df_day_activity_sleep``` afterwards, we can create a new dataframe called ```df_avg_actslp``` that will be grouped by ```id``` and then the columns will be averaged. 

# In[38]:


df_avg_actslp = df_day_activity_sleep.copy().groupby(by='id').mean().reset_index()


# In[39]:


df_avg_actslp.head(3)


# Now that we have the average steps taken per day for each individual, we can classify each of them into the 4 activity levels. 

# In[40]:


condlist = [
              df_avg_actslp.TotalSteps < 5000, 
              (df_avg_actslp.TotalSteps >= 5000) & (df_avg_actslp.TotalSteps < 7499),
              (df_avg_actslp.TotalSteps >= 7500) & (df_avg_actslp.TotalSteps < 9999),
              (df_avg_actslp.TotalSteps >= 10_000)
             ]
choicelist = ['sedentary', 'lightly active', 'moderately active', 'very active']

df_avg_actslp['activity_level'] = np.select(condlist, choicelist, default=np.nan)


# In[41]:


df_avg_actslp.head(3)


# We should also make sure that this worked for all of the rows, and there weren't any null values added to the dataframe. 

# In[42]:


df_info(df_avg_actslp, name='df_avg_actslp')


# Now we can create a new dataframe called ```df_pct_actlvl``` for 'df_percent_activity_level' that will be grouped by ```activity_level``` with the percent of individuals in each activity level.

# In[43]:


df_pct_actlvl = df_avg_actslp.activity_level.value_counts(normalize=True).reset_index()


# In[44]:


df_pct_actlvl.rename(columns={'index': 'activity_level', 'activity_level': 'percentage'}, inplace=True)
df_pct_actlvl.percentage *= 100


# In[45]:


df_pct_actlvl


# With this dataframe, we can plot the percentages of individuals in each activity level:

# In[46]:


fig, ax = plt.subplots(figsize=(12,12), facecolor='w')
plt.rcParams.update({'font.size': 20})
labels = ['Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active']

plt.pie(
        df_pct_actlvl.percentage, labels=labels,  startangle=113,
        autopct='%1.1f%%', pctdistance=0.85, colors=plt.cm.Reds_r(np.arange(75, 226, 50)), 
        wedgeprops={'linewidth': 8, 'edgecolor': 'white'}
        )
ax.add_artist(plt.Circle((0,0), 0.7, color='white'))

fig.suptitle('Percentage of Users \nin Each Activity Level', 
             x=0.52, y=0.5, fontsize=26, ha='center', va='center')

# plt.savefig('activity_levels.png', dpi=300, bbox_inches='tight')
plt.show()


# Somewhat surprisingly, the the largest activity level group among the FitBit users is actually the 'Sedentary' group. This may be surprising, considering that you might expect that only active individuals would seek out a health and fitness-focused smart device. Understanding this, Bellabeat should shift their marketing strategy to advertise towards not only active individuals, but also those who are sedentary. Beyond that, we can see that only a minority of the users reached the 'Very Active' level of 10,000 steps or more per day. This is considered unhealthy for most people, and Bellabeat could also market that their membership service will improve the health and fitness of subscribers as their activity level can be monitored and improved. 
# 
# 
# ```{admonition} Key Takeaways:
# :class: tip
# * Bellabeat should focus their marketing not only towards active individuals, but also those who are more sedentary.
# * Bellabeat should also market that their membership service will improve the health and fitness of subscribers as their activity level can be monitored and improved.
# ```

# ### 5.2 Weekly Trends in Steps and Sleep

# We can go beyond classifying the users into activity levels and try to identify trends in both steps and sleep per day of the week.  
# The goal behind this is that we may be able to identify two different trends in the data:
# 1. Are users taking the recommended 10,000 steps and sleeping the recommended 8 hours per day?
# 2. Do users display healthier habits on certain days of the week more than others?
# 
# With this information, Bellabeat will be able to identify if smart fitness device users are on average displaying healthy habits and provide in-app recommendations and reminders when users are not achieving healthy numbers or their personalized goals. As a result, Bellabeat will be able to identify if they should shift their marketing strategy to promote healthier fitness and sleeping habits, or whether their users are already doing well. Furthermore, Bellabeat will be able to market their app and membership as being able to help users achieve their health goals by improving their fitness and sleep. 
# 
# We can start of by taking a look at what the average steps and sleep per day of the week looks like. 
# 
# ````{margin}
# ```{tip}
# We don't have to actually assign a new variable for this dataframe, as plotting a barplot with seaborn will essentailly automatically take care of the calculations for us. 
# ```
# ````

# In[47]:


df_day_activity_sleep.groupby(by='day_of_week').mean().drop(columns='id').reset_index()


# Now, we can establish a week order to be used for all following plots. 

# In[48]:


WEEK_ORDER = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']


# Then we can plot the average steps taken by day of the week:

# In[68]:


fig, ax = plt.subplots(figsize=(12, 8), facecolor='w')
plt.rcParams.update({'font.size': 14})

sns.barplot(
            data=df_day_activity_sleep, x='day_of_week', y='TotalSteps', 
            order=WEEK_ORDER, palette='icefire', ci=None, alpha=0.8
            )
plt.text(x=-0.4, y=10_100, s='recommended daily steps', 
         color='red', ha='left')
plt.axhline(y=10_000, color='red', linestyle='--', linewidth=2)

ax.set_xlabel('Day of the Week', fontsize=16, labelpad=10)
ax.set_ylabel('Average Steps', fontsize=16, labelpad=10)
ax.yaxis.set_major_formatter(mpl.ticker.StrMethodFormatter('{x:,.0f}'))
ax.tick_params(axis='both', size=0)

ax.grid(axis='y', linestyle='--', alpha=0.8)
sns.despine(bottom=True, left=True)
fig.suptitle('Average Steps by Day of the Week',
             fontsize=20, x=0.13, y=0.95, ha='left')

# plt.savefig('steps_weekly.png', dpi=300, bbox_inches='tight')
plt.show()


# And then the average minutes of sleep by day of the week:

# In[50]:


fig, ax = plt.subplots(figsize=(12, 8), facecolor='w')
plt.rcParams.update({'font.size': 14})

sns.barplot(
            data=df_day_activity_sleep, x='day_of_week', y='TotalMinutesAsleep', 
            order=WEEK_ORDER, palette='icefire', ci=None, alpha=0.8
            )
plt.text(x=-0.4, y=485, s='recommended daily sleep (8 hours)', 
         color='red', ha='left')
plt.axhline(y=480, color='red', linestyle='--', linewidth=2)

ax.set_xlabel('Day of the Week', fontsize=16, labelpad=10)
ax.set_ylabel('Average Minutes Asleep', fontsize=16, labelpad=10)
ax.tick_params(axis='both', size=0)

ax.grid(axis='y', linestyle='--', alpha=0.8)
sns.despine(bottom=True, left=True)
fig.suptitle('Average Minutes Asleep by Day of the Week',
             fontsize=20, x=0.13, y=0.95, ha='left')

# plt.savefig('sleep_weekly.png', dpi=300, bbox_inches='tight')
plt.show()


# Interestingly, we can see that on average, the FitBit users are not reaching either the daily recommended steps or the daily recommended sleep. Coinciding with the earlier plot in 5.1, we can see that the users on average are not following healthy habits. Knowing this, Bellabeat should shift their marketing strategy to be more along the lines of being able to help their users achieve healthier fitness and sleeping habits. Beyond this, we can notice that there are some trends in both steps and sleep by day of the week. For example, the average steps taken per day seems to take a lull in the middle of the week from Wednesday until the weekend, and the lowest step count is seen on Sunday. With this in mind, Bellabeat should provide push notifications from their app reminding users to take a quick walk in order to fulfill their daily steps requirements. Similarly, we can see some slight increases in sleep on the weekend, but it takes a dip on the weekdays. Though the recommended 8 hours per day is not being followed, Bellabeat should send extra push notifications during the weekdays to remind users to wind down and try to get to bed early so that they can get their needed sleep. 
# 
# ```{admonition} Key Takeaways:
# :class: tip
# * Bellabeat should shift their marketing strategy to be more along the lines of 'most people don't have a healthy lifestyle--we can help you achieve one!'
# * Bellabeat should provide push notifications through their mobile app to remind users to take a quick walk or to get to bed early particularly during the weekdays since the majority of users are not following healthy fitness and health habits. 
# ```

# #### 5.2.2 Daily Sleep Analysis
# 
# Devling a bit further with regards to the sleep data, we can analyze to see the quality of sleep per day of the week.  
# Using the ```df_min_sleep``` dataframe, we can analyze the amount of time users are spending asleep, restless, and awake in bed while trying to sleep. We can also see if users are more restless on certain days of the week more than others. 

# The 'value' column has 3 values corresponding to the 3 different sleep states:
# 1: Asleep
# 2: Restless
# 3: Awake in bed
# 
# In this case, this visualization will be showing data for a single individual rather than for all individuals, so generalizations based on the data may not be possible, but we can see what the data looks like on an individual basis.  
# In order to calculate the time spent in each sleep state, adding a 'date' column will allow us to make sure that we only check dates where there is actually data for each individual. 

# In[51]:


df_min_sleep['day_of_week'] = df_min_sleep['date_time'].dt.day_name()
df_min_sleep['date'] = df_min_sleep['date_time'].dt.date


# In[52]:


df_min_sleep.head(3)


# And then we can use a funciton to plot the data with which we can supply a user ID and return their sleep data:

# In[53]:


def plot_sleep(df_min_sleep: pd.DataFrame, user_id: int, repeat_ylabel: bool = True):
    '''
    Plots sleep data for a given id
    
        Parameters:
            df_min_sleep (pd.DataFrame): Dataframe with sleep data to plot
            id (int):                    ID of the user to be analyzed
            repeat_ylabel (bool):        Whether to repeat y-axis label
    '''

    SLEEP_STATE = ['Asleep', 'Restless', 'Awake in Bed']

    fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(22, 8), facecolor='w')
    user_id = df_min_sleep.id.unique()[user_id]
    df_id = df_min_sleep.loc[df_min_sleep.id == user_id]
    
    for idx, ax in enumerate(axes):

        minutes = df_id.loc[df_id.value == idx + 1].groupby('day_of_week')['value'].sum()
        days = df_id.groupby('date').day_of_week.value_counts()

        days_count = {}
        for i in range(len(days)):
            days_count[days.index[i][1]] = days_count.get(days.index[i][1], 0) + 1

        for i in minutes.index:
            minutes[i] /= days_count[i]

        sns.barplot(
            orient='h', x=minutes.values, y=minutes.index, 
            palette='icefire', order=WEEK_ORDER, alpha=0.8, ax=ax
        )

        if not repeat_ylabel and idx > 0:
            ax.set_yticks([])
        ax.yaxis.set_tick_params(length=0)
        ax.set_ylabel('')
        ax.tick_params(axis='both', labelsize=14)
        ax.set_xlabel(xlabel=f'Minutes {SLEEP_STATE[idx]}', fontsize=14, labelpad=10)

        ax.set_title(f'Minutes {SLEEP_STATE[idx]} by Day of Week',
                    fontsize=16, loc='left', pad=20)

        ax.grid(axis='x', linestyle='--', alpha=0.8)
        sns.despine()
    
    fig.suptitle('Average Minutes Spent in Each Sleep State by Day of the Week', 
                 fontsize=22, x=0.123, y=1.05, ha='left')


# In[54]:


plot_sleep(df_min_sleep, user_id=0)
# plt.savefig('sleep_indiv.png', dpi=300, bbox_inches='tight')


# ````{div} full-width
# We can see that user 0 is only getting about 6 hours of sleep most days, while they sleep in on Sundays. Also, we can see that the user is mostly restless during the weekdays, particularly on Mondays and Thursdays. And finally, we can see that the user doesn't spend much time in bed awake, though on some particular days there seems to be a bit more time spent awake than others. With all of this information in mind, Bellabeat can market that with their membership service, they will be able to identify key areas of improvement for their users and indivudalize their suggestions. In particular, they will be able to identify key days where an individual user may be struggling, such as Thursdays for user 0, where they are spending a lot of time restless in bed and end up with little sleep. With these weaknesses identified, Bellabeat will be able to push notifications to the user to encourage them to take a quick walk or get to bed early. Finally, Bellabeat will be able to attract more users to their products and particularly to their subscription membership service, while also improving the sleep quality of their users. 
# 
# ```{admonition} Key Takeaways:
# :class: tip
# * Bellabeat should market that signing up for their subscription service will lead to a better sleep quality for their users with individualized suggestions and reminders for each user for every day of the week. 
# ```
# ````

# ### 5.3 Daily Trends in Steps and Calories

# We can go on to analyze what time of day users are most likely to be doing activity, resulting in steps and calories burned. With this knowledge, Bellabeat will be able to identify trends in what time of the day users are most likley to be able to do some form of activity, and can then provide push notifications to encourage users to start. Also, by understanding the time trends, Bellabeat will be able to better market their fashionable products, as if many users are getting in steps during the middle of the day, this suggests that the users are wearing their smart devices outside to work, etc., and Bellabeat would have the edge in that users may be more likely to wear a fashionable product rather than an upleasant one sold by competitors. 
# 
# We can start of by isolating the hours of the day and place them into a new column in ```df_hour_steps_calories```:

# In[55]:


df_hour_steps_calories['time'] = df_hour_steps_calories['date_time'].apply(lambda t: t.strftime('%H:%M'))


# In[56]:


df_hour_steps_calories.head(3)


# And then we can get right to plotting the data:

# In[57]:


fig, ax = plt.subplots(figsize=(12, 8), facecolor='w')
plt.rcParams.update({'font.size': 14})

sns.barplot(
            data=df_hour_steps_calories, x='time', y='StepTotal', 
            palette='icefire', ci=None, alpha=0.8, ax=ax
            )
ax.set_xlabel('Time', fontsize=16, labelpad=15)
ax.set_ylabel('Steps Taken', fontsize=16, labelpad=10)
ax.tick_params(axis='both', size=0)
ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
ax.grid(axis='y', linestyle='--', alpha=0.8)

ax2 = ax.twinx()
sns.lineplot(data=df_hour_steps_calories, x='time', y='Calories',
             marker='o', ax=ax2)
ax2.set_ylabel('Calories Burned', fontsize=16, labelpad=10)
ax2.tick_params(axis='both', size=0)
ax2.set_yticks([74, 85, 96, 107, 118, 129])

plt.text(4.3, 75, 'Calories Burned \u2192', color=plt.cm.Blues(0.8), ha='right')

sns.despine(bottom=True, left=True)
fig.suptitle('Steps Taken and Calories Burned by Time of Day',
             fontsize=20, x=0.13, y=0.95, ha='left')

# plt.savefig('steps_cal_day.png', dpi=300, bbox_inches='tight')
plt.show()


# We can see that the many of steps are taken around noon and lunchtime before dipping a bit midday, then the majority of steps are taken as the evening approaches. The calories burned seems to follow the number of steps taken quite closely, which is to be expected. Knowing that most steps are taken in the afternoon and evening, Bellabeat will be able to refine when they are sending push notifications to remind users to get their steps in, as they know which time of day their users are most likely to be able to get their steps in. Furthermore, Bellabeat should also focus their marketing on how their products are fashionable and can be worn to stand out everywhere, particularly places where users may be around lunchtime, for example at work or in a restaurant. 
#     
# ```{admonition} Key Takeaways:
# :class: tip
# * The majority of steps taken and calories burned occur around noon and in the evening, so Bellabeat should send push notifications to remind users to get their steps in at these times for maximum rates of success. 
# * Bellabeat should focus their marketing on how their products are fashionable and can be worn proudly at any time of the day, wherever users are. 
# ```

# ### 5.4 Daily Time of Device Usage
# 

# Another important metric that we can analyze is the amount of time each day for which users are wearing their device. This will help Bellabeat understand if a long-lasting battery is important to users of smart fitness devices. Beyond this, Bellabeat will also be able to identify whether they should shift their marketing strategy to highlight the long-lasting battery of their products.
# 
# We can start off with the ```df_day_activity_sleep``` dataframe and calculate the percentage of time each day for which users are wearing their device

# In[58]:


MINUTES_PER_DAY = 24 * 60
df_day_activity_sleep['percent_day_worn'] = df_day_activity_sleep.iloc[:, -5:-1].sum(axis=1) / MINUTES_PER_DAY


# Then we can group the data by user ID and calculate the average percent of usage per day

# In[59]:


df_worn = df_day_activity_sleep.groupby(by='id').mean()


# In[60]:


df_worn.head(3)


# Similar to what we did for the earlier plot in 5.1, we can once again classify the data into three categories for how long the user wears their device each day:  
# 1. Device is worn >= 90% of the day - All Day
# 2. Device is worn > 50% of the day - Most of the Day
# 3. Device is worn <= 50% of the day - Part of the Day

# In[61]:


condlist = [
            df_worn.percent_day_worn >= 0.9,
            df_worn.percent_day_worn > 0.5,
            df_worn.percent_day_worn <= 0.5            
            ]
choicelist = ['All Day', 'Most of the Day', 'Part of the Day']
df_worn['day_wear'] = np.select(condlist, choicelist, default=np.nan)


# In[62]:


df_info(df_worn)


# In[63]:


df_worn.day_wear.head(3)


# Then we can get what percent of the data fits into each category

# In[64]:


df_pct_worn = df_worn.day_wear.value_counts(normalize=True).reset_index()


# In[65]:


df_pct_worn


# And we are ready to plot the data:

# In[66]:


fig, ax = plt.subplots(figsize=(12,12), facecolor='w')
plt.rcParams.update({'font.size': 20})
labels = ['Most of the Day', 'All Day', 'Part of the Day']

plt.pie(
        df_pct_worn.day_wear, startangle=25, labels=labels,
        autopct='%1.1f%%', pctdistance=0.85, colors=plt.cm.Greens_r(np.arange(75, 226, 75)),
        wedgeprops={'linewidth': 8, 'edgecolor': 'white'}
        )
ax.add_artist(plt.Circle((0,0), 0.7, color='white'))
fig.suptitle('Time With Device\nWorn Per Day', 
             x=0.52, y=0.5, fontsize=30, ha='center', va='center')

# plt.savefig('use_pct.png', dpi=300, bbox_inches='tight')
plt.show()


# We can see that the majority of users are wearing their device most of the day or all day, but there are a few users who are wearing their device for less than 50% of the day. This is a good indication that Bellabeat should focus their marketing on how their devices can easily last all-day, as this will attract the most users to their products. Beyond this, it is also important to note that should Bellabeat develop a new device with a touchscreen, they should remember the importance of having a long-lasting battery, as the vast majority of users will be using their device for a very significant portion of the day, and consumers will look at battery life as a key factor in determining their purchase. 
# 
# ```{admonition} Key Takeaways:
# :class: tip
# * Bellabeat should focus their marketing on how their devices can easily last all-day, as users appear to use their device for a significant portion of the day. 
# * Bellabeat should keep in mind that the long-lasting battery of their devices is important to their users, and any future products that may be developed should have a long-lasting battery. 
# ```

# ## 6. Act
# <!-- <a name='Act-Phase'></a><h3 style="color:#FA8072">6. Act Phase:</h3> -->

# Returning to our business questions: 
# 
# 1. What are some trends in smart device usage?
# 2. How could these trends apply to Bellabeat customers?
# 3. How could these trends help influence Bellabeat’s marketing strategy?
# 
# With all of the analysis that we have done, and an emphasis on data-driven decision making, I would recommend the following for Bellabeat:
# 
# __1. Increase marketing towards sedentary and lightly active demographics.__
# 
# With the FitBit users, we were able to recognize that a majority of users (58.3%) classify under 'sedentary' or 'lightly active' demographics. Even though their products may be most tailored towards highly active individuals, the data suggests that the users buying these products are not always active. In order to maximize sales of their products, broadening their approach to wider demographics can bring in more customers for their products, which down the line can lead to increased membership purchases and even more increased revenue. 
# 
# __2. Market more towards the idea that Bellabeat devices can improve fitness, health, and sleep quality.__
# ````{margin}
# ```{tip}
# The Mayo Clinic recommends taking [10,000 steps per day](https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/10000-steps/art-20317391) as a healthy lifestyle measure to reduce the risk of many diseases. The CDC recommends [having a workout buddy](https://www.cdc.gov/diabetes/library/spotlights/workout-buddy.html) to help you stay motivated in your workouts.
# ```
# ````
# 
# The majority of FitBit users were not reaching the recommended 10,000 steps per day, nor were they sleeping for the recommended 8 hours per day, particularly on weekdays. With this in mind, Bellabeat should include in their marketing that most people are not following healthy guidelines right now, but with a Bellabeat product and membership, Bellabeat will be able to help them reach their health and fitness goals. Some examples of how Bellabeat may help their members and attract more customers may include:
# * using push notifications through the Bellabeat app to remind users to get their steps in and go to bed early
# * use the app to create a type of social environment where users can come together to compete for fitness goals
# * personalized advice for higher quality sleep for users recognized as having a low sleep quality
# * develop a smart watch with a touch screen that will track workout data and easily remind users with notifications without having to pull their phones out
# 
# __3. Put more emphasis on the fashionable aspects of Bellabeat products as well as their long-lasting batteries.__
# 
# The data shows that, on average, the FitBit users are wearing their devices for the vast majority of the day, including during periods when they are out in public. As a result, emphasizing the great looks of the Bellabeat products will entice potential customers, as customers are looking for a device they can be proud to wear all day. Furthermore, since the users are wearing their devices for long periods of time each day, marketing the long-lasting batteries of Bellabeat products with greater significance will also help to attract more customers, as customers are placing great value on the battery life of their devices. With this in mind, if Bellabeat develops any new products, this value on battery life should be considered every step of the way, such as with a potential new smart watch with a touchscreen. 

# __Thank you for reading through this case study!__
